eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8097/eureka
      # defaultZone: http://team6-eureka-server:8761/eureka

spring:
  config:
    # import: "optional:configserver:http://192.168.100.221:30633/"
    import: "optional:configserver:http://localhost:8761/"
